[package]
name = "midir-tui"
version = "0.2.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
midir = "0.9"
anyhow = "1.0"
directories = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
