name: security-audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # cargo-audit (RustSec)
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Run cargo audit
        run: cargo audit

      # cargo-deny (vulns + licenses)
      - name: Install cargo-deny
        run: cargo install cargo-deny --locked
      - name: Generate default cargo-deny config if missing
        run: |
          test -f deny.toml || cargo deny init --non-interactive
      - name: Run cargo-deny checks
        run: cargo deny check bans licenses sources vulnerabilities
